#include <Date.au3>
#include <FileConstants.au3>
#include <WinAPIFiles.au3>

Global $Today=_DateToDayValue(@YEAR,@MON,@MDAY),$Y, $M, $D
$Today=_DayValueToDate($Today, $Y, $M, $D)
$Y = StringTrimLeft($Y, 2)
$Today=StringFormat("%02i.%02i.%02i", $M,  $D,  $Y)

Func Daily($CSV, $Macro)

    ;Local Const $sFilePath = _WinAPI_GetTempFileName('C:\Program Files (x86)\Microsoft Office\root\Office16\Excel.exe')
    ;Local $iFileExists = FileExists($sFilePath)
    ;If $iFileExists Then
        Run('C:\Program Files (x86)\Microsoft Office\root\Office16\Excel.exe' & ' ' & $CSV, 'C:\Users\UserName\Documents\Reports\New')
    ;Else
    ;    Run('C:\Program Files (x86)\Microsoft Office\Office15\Excel.exe' & ' ' & $CSV, 'C:\Users\UserName\Documents\Reports\New')
    ;EndIf
    Sleep(8000)
    Send("!l")
    Sleep(1000)
    Send("pm")
    Sleep(1000)
    Send($Macro, 1)
    Send("{TAB 3}")
    Sleep(1000)
    Send("{ENTER}")
    Sleep(5000)
    Send("{HOME}")
    Sleep(1000)
    Send("!f")
    Sleep(1000)
    Send("a")
    Sleep(500)
    Send("c")
    Sleep(500)
    Send("y2")
    Sleep(2000)
    Send("{TAB}")
    Sleep(1000)
    Send("{DOWN}")
    Sleep(1000)
    Send("{UP 10}")
    Sleep(500)
    Send("{UP 10}")
    Sleep(500)
    Send("{UP 10}")
    Sleep(1000)
    Send("{ENTER}")
    Sleep(1000)
    Send("{SHIFTDOWN}")
    Send("{TAB}")
    Send("{SHIFTUP}")
    Sleep(500)
    Sleep(1000)
    Send("{ENTER}")
    Sleep(1000)
    Send("!{F4}")
    Sleep(500)
EndFunc

Func Report($CSV, $Macro)
    ;Local Const $sFilePath = _WinAPI_GetTempFileName('C:\Program Files (x86)\Microsoft Office\root\Office16\Excel.exe')
    ;Local $iFileExists = FileExists($sFilePath)
    ;If $iFileExists Then
        Run('C:\Program Files (x86)\Microsoft Office\root\Office16\Excel.exe' & ' ' & $CSV, 'C:\Users\UserName\Documents\Reports\New')
    ;Else
    ;    Run('C:\Program Files (x86)\Microsoft Office\Office15\Excel.exe' & ' ' & $CSV, 'C:\Users\UserName\Documents\Reports\New')
    ;EndIf
    Sleep(8000)
    Send("!l")
    Sleep(1000)
    Send("pm")
    Sleep(1000)
    Send($Macro, 1)
    Send("{TAB 3}")
    Sleep(1000)
    Send("{ENTER}")
    Sleep(5000)
    Send("{HOME}")
    Sleep(500)
    Send("!f")
    Sleep(500)
    Send("a")
    Sleep(500)
    Send("c")
    Sleep(500)
    Send("y2")
    Sleep(2000)
    Send("{TAB}")
    Sleep(1000)
    Send("{DOWN}")
    Sleep(1000)
    Send("{UP 10}")
    Sleep(500)
    Send("{UP 10}")
    Sleep(500)
    Send("{UP 10}")
    Sleep(1000)
    Send("{ENTER}")
    Sleep(1000)
    Send("{SHIFTDOWN}")
    Send("{TAB}")
    Send("{SHIFTUP}")
    Sleep(1000)
    Sleep(1000)
    Send("{ENTER}")
    Sleep(500)
    Send("!{F4}")
    Sleep(500)
    Send("!{F4}")
    Sleep(1000)
EndFunc

$FileExists = 0
$FileExists = FileExists('C:\Users\UserName\Documents\Reports\New\CR026 Computers Not Actively Reporting ' & $Today & '.csv')
If $FileExists Then Report('"C:\Users\UserName\Documents\Reports\New\CR026 Computers Not Actively Reporting ' & $Today & '.csv"', 'Macros.xlsm!CR026M')
Sleep(500)
$FileExists = 0
$FileExists = FileExists('C:\Users\UserName\Documents\Reports\New\CR063 Patch Levels ' & $Today & '.csv')
If $FileExists Then Report('"C:\Users\UserName\Documents\Reports\New\CR063 Patch Levels ' & $Today & '.csv"', 'Macros.xlsm!CR063M')
Sleep(500)
$FileExists = 0
$FileExists = FileExists('C:\Users\UserName\Documents\Reports\New\CR064 Computers Missing Patches ' & $Today & '.csv')
If $FileExists Then Report('"C:\Users\UserName\Documents\Reports\New\CR064 Computers Missing Patches ' & $Today & '.csv"', 'Macros.xlsm!CR064M')
Sleep(500)
$FileExists = 0
$FileExists = FileExists('C:\Users\UserName\Documents\Reports\New\CR066 Admin User Accounts ' & $Today & '.csv')
If $FileExists Then Report('"C:\Users\UserName\Documents\Reports\New\CR066 Admin User Accounts ' & $Today & '.csv"', 'Macros.xlsm!CR066M')
Sleep(500)
$FileExists = 0
$FileExists = FileExists('C:\Users\UserName\Documents\Reports\New\CR067 Computer Utilization (CR026) ' & $Today & '.csv')
If $FileExists Then Report('"C:\Users\UserName\Documents\Reports\New\CR067 Computer Utilization (CR026) ' & $Today & '.csv"', 'Macros.xlsm!CR067M')
Sleep(500)
$FileExists = 0
$FileExists = FileExists('C:\Users\UserName\Documents\Reports\New\CR068 Disk Space Usage ' & $Today & '.csv')
If $FileExists Then Report('"C:\Users\UserName\Documents\Reports\New\CR068 Disk Space Usage ' & $Today & '.csv"', 'Macros.xlsm!CR068M')
Sleep(500)
$FileExists = 0
$FileExists = FileExists('C:\Users\UserName\Documents\Reports\New\OS Report ' & $Today & '.csv')
If $FileExists Then Daily('"C:\Users\UserName\Documents\Reports\New\OS Report ' & $Today & '.csv"', "Macros.xlsm!Daily")
Sleep(500)
$FileExists = 0
$FileExists = FileExists('C:\Users\UserName\Documents\Reports\New\Hardware Report Full List of Hardware ' & $Today & '.csv')
If $FileExists Then Report('"C:\Users\UserName\Documents\Reports\New\Hardware Report Full List of Hardware ' & $Today & '.csv"', 'Macros.xlsm!HWReport')
$FileExists = 0
$FileExists = FileExists('C:\Users\UserName\Documents\Reports\New\Deployments ' & $Today & '.csv')
If $FileExists Then Report('"C:\Users\UserName\Documents\Reports\New\Deployments ' & $Today & '.csv"', 'Macros.xlsm!Deployments')


